### PR TITLE
update dependencies bump to go1.13

### PR DESCRIPTION
**Pull request by carnott-snap**

### CODE REVIEW

**Comment by unknwon** [comment]
Thanks for the PR!

But why is this change needed?

**Comment by carnott-snap** [comment]
go1.13 does not play nice with the invalid pseudo-version that is currently contained within your `go.mod` file:
```
github.com/go-macaron/cors@v0.0.0-20190309005821-6fd6a9bfe14e9: invalid pseudo-version: revision is longer than canonical (6fd6a9bfe14e)
```

You are welcome to just fixup the pseudo-version, but it seemed cleaner to bump the version of `gopkg.in/macaron.v1` and simplify the `go.mod` significantly.

**Comment by unknwon** [comment]
I see, but it seems missing all the indirect dependencies. Have you ran `go mod tidy`?

**Comment by carnott-snap** [comment]
Yes, `go mod tidy` is what cleaned most of those up. `gopkg.in/macaron.v1` used to not track its dependencies via Go modules, however not that this is corrected `// indirect` dependencies are not required in both places.

**Comment by unknwon** [comment]
I see, I guess it deletes all indirects because now `gopkg.in/macaron.v1` has **go.mod** file.

**Pull request merged**
